version: "3.4"
services:
  app:
    build: .
    image: euro-tours-app:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - config.env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db